{{- if .Values.ingress.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jenkins.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ template "jenkins.fullname" . }}"
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ template "jenkins.fullname" . }}"
              servicePort: {{ .Values.master.servicePort }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
